# Form implementation generated from reading ui file 'coin_app.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 457)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.coin_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.coin_add.setGeometry(QtCore.QRect(550, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.coin_add.setFont(font)
        self.coin_add.setObjectName("coin_add")
        self.find_info = QtWidgets.QLabel(parent=self.centralwidget)
        self.find_info.setGeometry(QtCore.QRect(10, 60, 531, 31))
        self.find_info.setText("")
        self.find_info.setObjectName("find_info")
        self.fresh_table = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fresh_table.setGeometry(QtCore.QRect(550, 60, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.fresh_table.setFont(font)
        self.fresh_table.setTabletTracking(False)
        self.fresh_table.setObjectName("fresh_table")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 531, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.coins_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.coins_table.setGeometry(QtCore.QRect(5, 110, 781, 301))
        self.coins_table.resizeColumnsToContents()
        self.coins_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.coins_table.setObjectName("coins_table")
        self.coins_table.setColumnCount(3)
        self.coins_table.setRowCount(250)
        self.coins_table.setHorizontalHeaderLabels(('Coin', 'Symbol', 'Price'))
        self.coins_table.setColumnWidth(0, 260)
        self.coins_table.setColumnWidth(1, 260)
        self.coins_table.setColumnWidth(2, 260)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coin App"))
        self.coin_add.setText(_translate("MainWindow", "Ekle"))
        self.fresh_table.setText(_translate("MainWindow", "Yenile"))
